title: FEDMED Workshop
description: FEDMED Workshop at ICIAP 2023
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
workshop:
  name: Workshop on Federated Learning in Medical Imaging and Vision
  short: FEDMED
  host: "ICIAP 2023<br>Udine, Italy<br>September 11-15, 2023"
  submission_link: #
  dates:
    submission: June 30, 2023
    decision: July 30, 2023
    camera_ready: August 15, 2023
    workshop: September 11-15, 2023 (TBD)
  organizers:
    - name: Simone
      surname: Palazzo
      affiliation: University of Catania
      email: simone.palazzo@unict.it
      pic: img/simone.jpg
    - name: Federica
      surname: Proietto Salanitri
      affiliation: University of Catania
      email: federica.proiettosalanitri@phd.unict.it
      pic: img/federica.jpg
    - name: Matteo
      surname: Pennisi
      affiliation: University of Catania
      email: matteo.pennisi@unicampus.it
      pic: img/pic.jpg
    - name: Chen
      surname: Chen
      affiliation: University of Central Florida
      email: chen.chen@crcv.ucf.edu
      pic: img/pic.jpg
    - name: Bruno
      surname: Casella
      affiliation: University of Turin
      email: bruno.casella@unito.it
      pic: img/bruno.jpg
    - name: Gianluca
      surname: Mittone
      affiliation: University of Turin
      email: gianluca.mittone@unito.it
      pic: img/gianluca.png
  pc:
    - name: Marco Aldinucci
      affiliation: University of Turin
    - name: Ulas Bagci
      affiliation: Northwestern University
    - name: Roberto Esposito
      affiliation: University of Turin
    - name: Mirko Polato
      affiliation: University of Turin
    - name: Concetto Spampinato
      affiliation: University of Catania
